package domain.model;

public enum ContractClauseCode {
    STANDARD_TERMS,
    MORTGAGE_GUARANTEE_REQUIRED,
    LONG_TERM_INSURANCE_CLAUSE,
    ADDITIONAL_GUARANTOR_REQUIRED,
    MANDATORY_LIFE_INSURANCE,
    FIRST_TIME_BUYER_REDUCED_FEES,
    JOINT_LIABILITY_CLAUSE
}
